# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 296c42cf8f7c91c9f02991fa12b5fcca7e66a6263cab535ca9c83bb9fc17966bb93fb4e6a3b873ef4ca55c8d725f3405101c30a2c14e4214892ce821ce7db45c

test:
  secret_key_base: 936c7c99870077227e23323b97aa1fc319873ced87e808348bbfaaee75d0f38cc50c49ece8588ff6a4e11ac75a4e80cf5f078260e68791baa5ceafd15b109daf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
